### ISSUE TITLE
How to test is file is executable?

### ISSUE THREAD

**Issue by endemics** [goss-org/goss#1009]
Hi,

I am looking at converting some serverspec tests to goss, where I  used to check if a file was executable using something like:
```
describe file('/path/to/file') do
    it { should be_file }
    it { should be_executable }
end
```
That is, I want to guarantee that a file exists and is executable, but do not want to mandate a specific mode.

Unless mistaken this is not supported in goss `file` test yet? What is the best way to check for that? Is it using a command output with `bash test -x /path/to/file` or is there better alternatives?

Thanks

**Comment by endemics** [comment]
The best I have found so far to implement the test is to use `match-regexp` and check that there is an execution bit on each digit
```
file:
  '/path/to/file':
    exists: true
    filetype: file
    mode:
      match-regexp: '[0-9][1357][1357][1357]'
```
