### ISSUE TITLE
Feature Request: Improve gomega matchers

### ISSUE THREAD

**Issue by aelsabbahy** [goss-org/goss#538]
**Describe the feature:**

Improve gomega matchers.

**Describe the solution you'd like**

1. Allow transforms. For example the following should work (fixes #350)
```yaml
kernel-param:
  net.core.somaxconn:
    value:
      gt: 5000
```

2. Add more gomega matchers, for example, the matchallelements matcher for slices.
https://onsi.github.io/gomega/#gstruct-testing-complex-data-types
