### ISSUE TITLE
Disk space alarm

### ISSUE THREAD

**Issue by keithy** [goss-org/goss#753]
Suggesting an official and improved version of something like this:
```
         command:
            "disk_space_alert(>=95%)":
               exit-status: 0
               exec: "df --exclude-type=tmpfs --exclude-type=devtmpfs --local"
               stdout: ["!/\\s(100|9[5-9])%/"] # >= 95%
               stderr: []
               timeout: 3000 #ms
               skip: false    
```
