### ISSUE TITLE
Support querying snap packages

### ISSUE THREAD

**Issue by nbirnel** [goss-org/goss#779]
**Describe the feature:**

Support for `snap` packages.

**Describe the solution you'd like**

`snap` would be added to the valid package types for the `--package` option.

`goss --package snap add package certbot`

**Describe alternatives you've considered**

Something like this works:
```
command:
  certbot-installed-with-snap:
    exit-status: 0
    exec: snap list certbot | grep '^certbot\s' >/dev/null
```

but is, in my opinion, less clear.
