### ISSUE TITLE
Support multiple valid values for the `file.mode` check

### ISSUE THREAD

**Issue by samuel-phan** [goss-org/goss#782]
**Describe the feature:**

Support multiple valid values instead of just one for a check.

Eg:

```yaml
file:
  /foo:
    exists: true
    mode: "0644"
```

but if on a host, the file has the mode `0444`, I want to consider it as `good` also.

**Describe the solution you'd like**

Instead of supporting only 1 value for `mode`, it could support a list of valid `modes`.

```yaml
file:
  /foo:
    exists: true
    mode:
      - "0644"
      - "0444"
```

**Describe alternatives you've considered**

I don't know any workaround except dropping the `file.mode` check.
