### ISSUE TITLE
Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by kmonticolo** [goss-org/goss#797]
**Describe the bug**
Rarely I got a syntax error from goss:
"./goss: 1: Syntax error: redirection unexpected" and I got non-zero exit code.

**How To Reproduce**
it's hard to reproduce, I got it 2-3 times during thousand runs.
I ran it like this: "./goss -g test-dir/country/goss.yaml v"

**Expected Behavior**
No "Syntax error", goss should working normally.

**Actual Behavior**
Rarely I got a syntax error from goss:
"./goss: 1: Syntax error: redirection unexpected"
It's very rarely hapen so it's not easy to reproduce.

**Environment:**
 - Version of goss    v0.3.20

 - OS/Distribution version (if applicable)
 - Linux pve01vm121-stage 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
+ hostnamectl
         Icon name: computer-vm
           Chassis: vm
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-17-amd64
      Architecture: x86-64

**Comment by ripienaar** [comment]
We'd need to see the yaml file causing it.

**Comment by aelsabbahy** [comment]
Is your ./goss a shell script wrapping goss by any chance?

What do these say on good vs bad runs?
```
file ./goss
md5sum ./goss
```

Possibly, if you're downloading goss prior to every run, perhaps the download is an HTML error file with `<...>` type symbols confusing sh/bash?

Hard to tell without understanding your flow a bit better. If it is in fact being downloaded on every execution, perhaps add a call to `md5sum ./goss` and see if the error cases have the same checksum.


> We'd need to see the yaml file causing it.

This also would be helpful.

**Comment by kmonticolo** [comment]
No, it was not a shell script, I just ran it like that because I did not add it to PATH.
Previously I downloaded it from github site, but now I copied it to local repo to avoid downloading it from github for each time.

```
$ md5sum $(which goss)
315bfaa776f502fb2ecafb1bd93ff56f  goss
$ goss -v
goss version v0.3.20
```
yaml file consists of multiple command invokes, here is an example:
```
command:
  mysql --login-path=shared -u mysql_ro -h 10.1.10.230 -P 3306 db1 -e 'describe table1':
    exit-status: 0
    stdout:
    - "Field\tType\tNull\tKey\tDefault\tExtra"
    - "created\tdatetime\tNO\tPRI\tNULL"
    - "something\tint(10) unsigned\tNO\t\tNULL"
    - "<redacted>"
    stderr: []
    timeout: 10000
  mysql --login-path=shared -u mysql_ro -h 10.1.10.230 -P 3306 db1 -e 'describe table2':
    exit-status: 0
    stdout:
    - "Field\tType\tNull\tKey\tDefault\tExtra"
    - "id\tint(10) unsigned\tNO\tPRI\tNULL\tauto_increment"
    - "<redacted>"
    stderr: []
    timeout: 10000
```
and I run it: 
```
 goss -g path/to/goss.yaml v
```
