### ISSUE TITLE
Command exec - multiple command in a single yaml file

### ISSUE THREAD

**Issue by Raghuchn** [goss-org/goss#798]
Hi,

I am trying to execute multiple commands(goss) in a single yaml file, but not successful in it.

When validate, i get only the output for "python" and not for "datetimectl"

####################################################
Output:

Command: version: exit-status: matches expectation: [0]
Command: version: stdout: matches expectation: [Python 3.8.13]

#######################################################

Can someone suggest what am i doing wrong here.

```
command:
  version:
    exit-status: 0
    exec: timedatectl
    stdout:
     - "NTP service: active"
    stderr: []
    exec: python --version
    stdout:
     - "Python 3.8.13"
    stderr: []
```

Thanks in Advance!!

**Comment by ripienaar** [comment]
You need to make 2 command blocks for this

```yaml
command:
  python --version:
    stdout:
    - 'Python 3.8.13'
  timedatectl:
    exit-status: 0
    stdout:
    - 'NTP service: active'
```
