### ISSUE TITLE
Breaking change in v0.4.0-rc.1 needs release doc fix

### ISSUE THREAD

**Issue by gberche-orange** [goss-org/goss#824]
**Describe the bug**

Given the following goss.yaml passing in 0.3.23

```
command:
  mysql-connect:
    exec: | 
       mysql -h 10.69.0.32 --database=default -u default -pommitedpassword        -e 'DROP TABLE IF EXISTS TEST; create table TEST(test_id int auto_increment, test_value int, primary key(test_id)); INSERT INTO TEST (TEST_VALUE) VALUES (1993);SELECT * FROM TEST'
    exit-status: 0
    stdout:
      - 1993 # make sure 1993 is present in the outout
    stderr: []
```

I would expect the test to pass in v0.4.0-rc.1 as I did not spot a related breaking change in release note. However it fails, likely related to int patterns

```
goss validate
.F

Failures/Skipped:

Command: mysql-connect: stdout:
Error
    HavePatterns matcher expects patterns to be a string. got: 
        <int>: 1993

Total Duration: 0.084s
Count: 2, Failed: 1, Skipped: 0
```

**Expected Behavior**

Add breaking change into https://github.com/goss-org/goss/releases/tag/v0.4.0-rc.1 such as:

```
Integer assertions such as the following 
\```yaml
    stdout:
      - 1993
\```

need to be expressed as string such as:

\```yaml
    stdout:
      - "1993"
\```
```

ps: github does not allow PRs  against releases body such https://github.com/goss-org/goss/releases/tag/v0.4.0-rc.1 I see some projects also maintaining a CHANGELOG.md (e.g. https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md ) file for documenting breaking changes, therefore enabling contributions on this file.
