### ISSUE TITLE
Validate with json formatting always returns `successful: false` even for successful tests

### ISSUE THREAD

**Issue by pahaeanx** [goss-org/goss#840]
**Describe the bug**
After upgrading from `0.3.x` to `0.4.1` I noticed that all my tests were failing, or at least it looked like it as I use the `json` output and decide based on a tests `successful` field.

With `0.4.x` it seems that this field is always `false`, even for tests that succeeded.

**How To Reproduce**
```yaml
# file: goss.yaml
command:
  Always-succeeds:
    exec: /bin/true
    exit-status: 0
  Always-fails:
    exec: /bin/false
    exit-status: 0
```
```shell
goss v -f json | jq '.results[].successful'
false
false
```

**Expected Behavior**
I'd expect successful tests to have their `successful` field to be `true` as was the case before `0.4.x`.

**Actual Behavior**
See above. Seems the `successful` field is always set to `false` and does not accurately reflect if a test has actually failed or not. 

**Environment:**
 - Version of goss: 0.4.1
