### ISSUE TITLE
Dinamic variables and envs

### ISSUE THREAD

**Issue by legolego621** [goss-org/goss#866]
Hello, can I use dinamic variables and envs like this?

```
command:
  kubectl get nodes:
    exit-status: 0
    stdout:
      not:
        match-regexp: 'NotReady'
  export test="a":
    exit-status: 0



http:
  '{{.Env.test}}':
    status: 200
    timeout: 5000
```
