### ISSUE TITLE
Set a custom user agent string for http checks

### ISSUE THREAD

**Issue by fbartels** [goss-org/goss#882]
**Describe the feature:**

- currently when goss performs a http check like below, `"Go-http-client/1.1"` will be sent to the server as the user agent

```
http:
  https://www.google.com:
    status: 200
    allow-insecure: false
    no-follow-redirects: false
    timeout: 1000
    username: ""
    password: ""
    ca-file: ""
    cert-file: ""
    key-file: ""
    proxy: ""
    skip: false
    method: GET
```

**Describe the solution you'd like**

- either goss should set its own user agent (like goss/0.4.4) or allow overriding the user agent on a per check basis

**Describe alternatives you've considered**

- none

**Comment by aelsabbahy** [comment]
Make sense, marked as approved. Feel free to submit a PR if you're interested in the change otherwise, I'll eventually get around to it.

**Comment by catdevman** [comment]
I'm going to take a shot at this if no one else is already working on it.

**Comment by catdevman** [comment]
@fbartels just FYI you can override this on a per check basis. 

```yaml
http:
  https://www.google.com:
    status: 200
    allow-insecure: false
    no-follow-redirects: false
    timeout: 1000
    username: ""
    password: ""
    ca-file: ""
    cert-file: ""
    key-file: ""
    proxy: ""
    skip: false
    method: GET
    request-headers:
        - 'user-agent: whatever/you/want/goes/here'
```
