### ISSUE TITLE
Semver package check did not work with alpine packages

### ISSUE THREAD

**Issue by gimler** [goss-org/goss#920]
**Describe the bug**
Semver versions check for package doesn't work with alpine packages. The actual package version for curl is `8.5.0-r0`

**How To Reproduce**
```
matching:
  td-agent:
    content:
      - 8.5.0-r0
    matches:
      and:
        - contain-element:
            semver-constraint: ">=8.5.0"
```

`>=8.4.0` is green. it seams that `-r0` is interpreted as release candidate

**Expected Behavior**
valid

**Actual Behavior**
error

**Environment:**
 - Version of goss 0.4.7
 - OS/Distribution version (if applicable) alpine
